### ISSUE TITLE
SFA/SFB is not getting created.

### ISSUE THREAD

**Issue by newmluser** [PacktPublishing/Enterprise-Augmented-Reality-Projects#2]
I am using Andriodstudio4.0 and Sceneform-1.15.0.
I followed all the steps mentioned in the chapter- "Adding Sceneform to the project".

After I follow the steps for creating .sfa and .sfb. when I click Finish.
noting is happening.

I see lot of open questions on the same topic in StackOverflow also.
Can you please let me know how I can use Andriod4.0 and get these assets getting imported?

**Comment by newmluser** [comment]
If sfa/sfb is not supported than can you suggest me how I can have create a AR App using ARcore

**Comment by shubham763** [comment]
Hi @newmluser 
- SceneForm 1.15.0 is indeed giving problems to create sfa/sfb files in Android Studio 4, it crashes during the process of converting an obj file to sfa/sfb and doesn't seem to have an easy solution at the moment.
- According to the official repository https://github.com/google-ar/sceneform-android-sdk Sceneform has changed from a closed sourced status to open source, not longer been available as an Android Studio Plugin (the latest plugin available is 1.15.0). Version 1.16.0 of Sceneform must be downloaded and included manually inside the project and instead of using sfa/sfb files, it favours now gltf (specifically .glb, which includes textures, animations etc. inside an only file) files.

I, therefore, see three approaches:

1) To use the new Sceneform 1.16.0 and glb files for the models. This would be my primary approach. For this, the user needs to:
 - First, have his models in .glb format. .glb files can be directly exported from the main modelling programs such as Blender, Maya and others or there are online converters that easily convert obj and similar files to glb. More information can be found at the official glTF page: https://www.khronos.org/gltf/
- The main page https://github.com/google-ar/sceneform-android-sdk provides instructions on how to add the 1.16.0 version to any project but I would recommend to directly download the repository and open the provided gltf sample inside it, as it works by itself and it's a good starting point to see how it works, and then modify the code as needed. 
- Finally, to load the glb model locally in Android Studio, instead of using a remote url, you can create an assets folder in your project (right click on app - New - Folder - Assets Folder) and copy the glb files inside it. Then, in the URI.parse call of the ModelRenderable.builder instead of calling to an url like in the example you would only have to call the name of the model, something like Uri.parse("model.glb") (or "folder_name/model.glb" in case it's placed inside another folder under assets).

2) If you really need to use .obj files for whatever reason instead of glb files, you can download and follow the new ARCore sample project https://github.com/google-ar/arcore-android-sdk/tree/master/samples/hello_ar_java where an obj file (andy.obj) is used. However, this method uses OpenGL directly and apart from being difficult to learn, it doesn't allow more than one texture per model which is a handicap in most cases.  

3) Use a 3D oriented program such as Unity instead of Android Studio, which accepts nearly any type of 3D models and integrates ARCore either through the sdk https://developers.google.com/ar/develop/unity/quickstart-android or directly inside its ARFoundation package https://github.com/Unity-Technologies/arfoundation-samples
